[package]
name = "libchintama"
version = "0.1.0"
authors = ["Yushi OMOTE <yushiomote@gmail.com>"]
edition = "2018"

[dependencies]
quicksilver = "0.3"
specs = "*"
specs-derive = "*"
serde = { version = "1.0", features = ["derive"] }
