[package]
name = "gunma"
version = "0.1.0"
authors = ["Yushi OMOTE <yushiomote@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.18"
ncollide2d = "0.19"
quicksilver = { version = "0.3", features = ["ncollide2d", "nalgebra"] }
specs = "*"
specs-derive = "*"
serde = { version = "1.0", features = ["derive"] }
